-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 22:58:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RestoGo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RestoGo` ;

-- -----------------------------------------------------
-- Schema RestoGo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RestoGo` DEFAULT CHARACTER SET utf8 ;
USE `RestoGo` ;

-- -----------------------------------------------------
-- Table `RestoGo`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestoGo`.`Cliente` (
  `email` VARCHAR(45) NOT NULL,
  `token` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestoGo`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestoGo`.`Pedido` (
  `idPedido` INT NOT NULL,
  `TokenRestaurante` VARCHAR(45) NOT NULL,
  `Cliente_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`),
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_email`)
    REFERENCES `RestoGo`.`Cliente` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pedido_Cliente_idx` ON `RestoGo`.`Pedido` (`Cliente_email` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


